universe: ["SPY","QQQ","AAPL","MSFT","NVDA","AMZN","META","GOOGL","TSLA","JPM","XOM","AVGO","LLY","UNH","V","MA","HD","BAC","COST","PEP"]
data_path: "data/combined.csv"
out_root: "outputs"
state_root: "state"