name: Daily Swing Scan

on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  swing:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install swing_systems package
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install yfinance pandas numpy pyyaml requests

      - name: Build combined.csv
        timeout-minutes: 20
        run: |
          START=$(date -u -d '30 days ago' +%F)
          python -m swing_systems.bin.build_data \
            --universe configs/universe.yaml \
            --start "$START" \
            --batch 200 \
            --sleep 0.05 \
            --top 150 \
            --multi

      - name: Build watchlists per strategy
        run: |
          python -m swing_systems.bin.build_watchlists \
            --combined data/combined.csv \
            --outdir configs/watchlists \
            --lookback 90

      - name: Run all strategy scanners
        run: |
          python -m swing_systems.bin.run_double_seven \
            --universe configs/universe.yaml \
            --include-file configs/watchlists/double_seven.yaml
          python -m swing_systems.bin.run_rsi2_us \
            --universe configs/universe.yaml \
            --include-file configs/watchlists/rsi2_us.yaml
          python -m swing_systems.bin.run_rsi2_5_70_sso \
            --universe configs/universe.yaml \
            --include-file configs/watchlists/rsi2_5_70_sso.yaml
          python -m swing_systems.bin.run_connors_3d_hl \
            --universe configs/universe.yaml \
            --include-file configs/watchlists/connors_3d_hl.yaml

      - name: Package results
        run: |
          mkdir -p docs
          echo "" > docs/.nojekyll
          echo "<meta http-equiv='refresh' content='0; url=swing-results-latest.zip'>" > docs/index.html
          ZIP_NAME="swing-results-$(date -u +'%Y%m%d').zip"
          zip -r "docs/$ZIP_NAME" outputs state data/combined.csv configs/watchlists
          cp "docs/$ZIP_NAME" docs/swing-results-latest.zip

      - name: Commit & push updates
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add outputs/** state/** docs/** configs/watchlists/**
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Auto-update results $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
            git push origin main
          fi